version: '3'
services:
  #App Service
  app:
    build:
      context: .
      args:
        NODE_VERSION: 12.18.3
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./www:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx:/var/log/nginx/
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mariadb:10.5
    container_name: mysql
    restart: unless-stopped
    command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
      - ./.docker/log/mysql:/var/log/mysql
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
      
  #PHP Myadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    networks:
      - app-network

##Docker Networks
networks:
  app-network:
    driver: bridge
