version: '3'
services:
  #App Service
  app:
    build:
      context: .
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    expose:
      - "9000"
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./www:/var/www/html
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx:/var/log/nginx/
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network
  #elasticsearch
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    networks:
      - app-network
    depends_on:
      - elasticsearch
    restart: unless-stopped
    ports:
      - 5601:5601
  # MySQL Service
  mysql:
    image: mariadb:10.5
    container_name: mysql
    restart: unless-stopped
    command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
      - ./.docker/log/mysql:/var/log/mysql
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
      
  #PHP Myadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: 'phpmyadmin'
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - '8080:80'
    networks:
      - app-network

##Docker Networks
networks:
  app-network:
    driver: bridge
